### ISSUE TITLE
이미지 주소 뒤에 불필요한 주소가 붙어있

### ISSUE THREAD

**Issue by lovit** [snudm/naver-blog-crawler#10]
![image](https://cloud.githubusercontent.com/assets/3401574/5800347/b4312558-a020-11e4-8281-b6601c254ac0.png)

이미지 주소 뒤에 ?type=s88 제거해야 함

**Comment by misuke88** [comment]
Fixed by 60c8d212a6a69740e3d3a1edbddad43afc1e2690
